---
rules:
  - name: "add a rule at a specific location in the rulebase"
    rule_name: 'SSH permit'
    description: 'SSH rule test the new fw'
    source_zone: ['Data_Zone'] 
    destination_zone: ['Data_Zone'] 
    source_ip: ['any']
    destination_ip: ['PA_Remote_Access']
    category: ['any']
    application: ['any']
    service: ['DNS'] 
    log_end: true
    action: 'allow'
    location: 'before'
    existing_rule: 'Allow'
    state: "present"  # Options: 'present', 'replaced', 'absent'
